source 'https://supermarket.chef.io'
cookbook 'build-essential', '= 3.2.0'
cookbook 'ohai', '= 3.0.1'
cookbook 'php', '~> 1.9.0'
cookbook 'nfs', '~> 2.2.8'
cookbook 'perlbrew', '~> 0.3.0'
cookbook 'onddo_proftpd', '~> 2.1.0'
cookbook 'cron', '~> 1.7.6'
cookbook 'aws', '>= 2.2.2'
